image: jangrewe/gitlab-ci-android
before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

stages:
- dependencies
- build
- test

dependenciesDownload:
  stage: dependencies
  script:
  - ./gradlew app:dependencies
  only:
    - /^CI-Test.*$/

lintDebug:
  stage: build
  script:
  - ./gradlew lintDebug

testDebug:
  stage: test
  script:
  - ./gradlew testDebug
